localizeapp/core/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from localizeapp.auth.models import User


class RegisterForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Email(message=None), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )

    def validate(self, extra_validators=None):
        initial_validation = super(RegisterForm, self).validate(extra_validators)
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Passwords must match")
            return False
        return True

localizeapp/localize/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, SelectField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from localizeapp.auth.models import User


class TaskForm(FlaskForm):
    title = StringField(
        "title",
        validators=[
            DataRequired(),
            Length(
                min=10,
                max=255,
                message="Kindly add meaningful title b/n 10 to 255 characters of length",
            ),
        ],
    )
    target_language = SelectField(
        "target_language", choices=[(1, "Hindi"), (2, "Spanish"), (3, "Japanese")]
    )

localizeapp/__init__.py
from decouple import config
from flask import Flask, render_template
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object(config("APP_SETTINGS"))

login_manager = LoginManager()
login_manager.init_app(app)
# login_manager.login_view = 'login'

bcrypt = Bcrypt(app)
db = SQLAlchemy(app)
migrate = Migrate(app, db)

# Registering blueprints
from localizeapp.auth.models import User
from localizeapp.auth.views import auth_blueprint
from localizeapp.core.views import core_blueprint
from localizeapp.localize.views import localize_blueprint

app.register_blueprint(auth_blueprint)
app.register_blueprint(core_blueprint)
app.register_blueprint(localize_blueprint)

login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

localizeapp/core/views.py
from flask import Blueprint, render_template
from flask_login import login_required

core_blueprint = Blueprint("core", __name__)


@core_blueprint.route("/")
@login_required
def home():
    return render_template("core/index.html")

localizeapp/localize/views.py
import lokalise
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

localize_blueprint = Blueprint("localize", __name__)
import pdb

from .forms import TaskForm

client = None
_token = None
_project_id = None
_key = None
_langs = None
_user = None


def get_client():
    from flask import current_app as app

    global client, _token, _project_id, _key, _user, _langs
    if not client:
        _token = app.config.get("LOCALIZE_API_KEY")
        _project_id = app.config.get("LOCALIZE_PORJECT_ID")
        _key = app.config.get("LOCALIZE_PROJECT_KEY")
        _user = app.config.get("LOCALIZE_PORJECT_USER")
        client = lokalise.Client(_token)
        _langs = [
            (l.lang_id, l.lang_name, l.lang_iso)
            for l in client.project_languages(_project_id).items
        ]
    return client


def create_task(client, form):
    target_lang = None
    i = None
    choice = None
    for i, i_choice in form.target_language.choices:
        if i == int(form.target_language.data):
            choice = i_choice
            break
    for i, lang_name, lang_iso in _langs:
        if choice in lang_name:
            target_lang = (i, lang_iso)
            break
    params = {}
    params["keys"] = [_key]
    params["title"] = form.title.data
    params["source_language_iso"] = "en"
    params["languages"] = [{"language_iso": target_lang[1], "users": [_user]}]
    return client.create_task(_project_id, params)


@login_required
@localize_blueprint.route("/localize/tasks", methods=["GET", "POST"])
def tasks():
    client = get_client()
    form = TaskForm(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            create_task(client, form)
    tasks = client.tasks(_project_id)
    return render_template("localize/tasks.html", form=form, tasks=tasks)

localizeapp/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>LocalizeApp - Flask User Management</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename="styles.css")}}">
    {% block css %}{% endblock %}
  </head>
  <body>

    {% include "navigation.html" %}

    <div class="container">

      <br>

      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
           {{message}}
           <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
        </div>
        <div class="col-md-4"></div>
      </div>
      {% endif %}
      {% endwith %}

      <!-- child template -->
      {% block content %}{% endblock %}

    </div>

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" type="text/javascript"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
  </body>
</html>

localizeapp/templates/core/index.html
{% extends "_base.html" %}
{% block content %}

<h1 class="text-center">Welcome {{current_user.email}}!</h1>

{% endblock %}

localizeapp/templates/localize/tasks.html
{% extends "_base.html" %}



<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <main class="form-signin w-100 m-auto">
            {% block content %}
            {% if tasks %}
            <h1 class="text-center">Tasks</h1>
            <ol>
                {% for task in tasks.items %}
                <li>{{ task.title }}</li>
                {% endfor %}
            </ol>
            {%else %}
                <h1 class="text-center">No tasks so far</h1>
            {% endif %}
            <form role="form" method="post" action="">
                {{ form.csrf_token }}
                <h1 class="h3 mb-3 fw-normal text-center">Create task</h1>

                <div class="form-floating">
                    {{ form.title(placeholder="title", class="form-control mb-2") }}
                    {{ form.title.label }}
                    {% if form.title.errors %}
                    {% for error in form.title.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-floating">
                    {{ form.target_language(placeholder="target_language", class="form-control mb-2") }}
                    {{ form.target_language.label }}
                    {% if form.target_language.errors %}
                    {% for error in form.target_language.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Create new task</button>
            </form>
            {% endblock %}
        </main>
    </div>
    <div class="col-md-4"></div>
</div>

localizeapp/templates/navigation.html
<!-- Navigation -->
<header class="p-3 text-bg-dark">
	<div class="container">
	  <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
		<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
		  <li><a href="{{ url_for('core.home') }}" class="nav-link px-2 text-secondary">Home</a></li>
		  <li><a href="{{ url_for('localize.tasks') }}" class="nav-link px-2 text-secondary">Localize - Tasks</a></li>
		  <li><a href="{{ url_for('localize.tasks') }}" class="nav-link px-2 text-secondary">Localize - Translation</a></li>
		</ul>
  
		<div class="text-end">
		  {% if current_user.is_authenticated %}
		  <a href="{{ url_for('auth.logout') }}"><button type="button" class="btn btn-danger me-2">Logout</button></a>
		  {% else %}
			<a href="{{ url_for('auth.login') }}"><button type="button" class="btn btn-outline-light me-2">Login</button></a>
			<a href="{{ url_for('auth.register') }}"><button type="button" class="btn btn-success">Sign up</button></a>
		  {% endif %}
			
		</div>
	  </div>
	</div>
  </header>